[package]
name = "synthesizer"
version = "0.5.1"
authors = []
edition = "2021"
readme = "README.md"
resolver = "2"
description = ""
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aura-api-helper = { git = "https://github.com/empathic-ai/aura-api-helper.git" }
base64 = "0.21.5"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
bytes = "1.5.0"
anyhow = "1.0.71"
tokio = { version = "1.32.0", default-features = false, features = ["macros", "rt"] }
lazy_static = "1.4.0"
futures = "0.3.25"
futures-util = "0.3.25"
#[target.'cfg(not(target_arch = "xtensa"))'.dependencies]
reqwest = { version = "0.11.13", features = ["json", "stream"] }
async-trait = "0.1.75"

[target.'cfg(all(not(target_arch = "wasm32")))'.dependencies]
openai-api-rs = { git = "https://github.com/Catchawink/openai-api-rs.git", branch = "streaming" }
